/* Replace with your SQL commands */

INSERT INTO `tag`
VALUES (1, '.NET', NULL, NULL),
       (2, 'AB Tasty', NULL, NULL),
       (3, 'ADO.NET', NULL, NULL),
       (4, 'AIX', NULL, NULL),
       (5, 'AMOA', NULL, NULL),
       (6, 'AMOE', NULL, NULL),
       (7, 'API', NULL, NULL),
       (8, 'ASP.NET', NULL, NULL),
       (9, 'ASP.NET MVC', NULL, NULL),
       (10, 'AT Internet', NULL, NULL),
       (11, 'AWS Fargate', NULL, NULL),
       (12, 'Abap', NULL, NULL),
       (13, 'Accessibilité', NULL, NULL),
       (14, 'Achats', NULL, NULL),
       (15, 'Acquisition trafic', NULL, NULL),
       (16, 'ActionScript', NULL, NULL),
       (17, 'Active Directory', NULL, NULL),
       (18, 'Ada', NULL, NULL),
       (19, 'Administration réseaux', NULL, NULL),
       (20, 'Administration système', NULL, NULL),
       (21, 'Adobe AIR', NULL, NULL),
       (22, 'Adobe After Effects', NULL, NULL),
       (23, 'Adobe Audition', NULL, NULL),
       (24, 'Adobe Character Animator', NULL, NULL),
       (25, 'Adobe Creative Suite', NULL, NULL),
       (26, 'Adobe Dreamweaver', NULL, NULL),
       (27, 'Adobe Edge', NULL, NULL),
       (28, 'Adobe Flash', NULL, NULL),
       (29, 'Adobe Flex', NULL, NULL),
       (30, 'Adobe Illustrator', NULL, NULL),
       (31, 'Adobe InDesign', NULL, NULL),
       (32, 'Adobe Lightroom', NULL, NULL),
       (33, 'Adobe Muse', NULL, NULL),
       (34, 'Adobe Photoshop', NULL, NULL),
       (35, 'Adobe Premiere', NULL, NULL),
       (36, 'Adobe Soundbooth', NULL, NULL),
       (37, 'Adviso', NULL, NULL),
       (38, 'Affiche', NULL, NULL),
       (39, 'Affiliation', NULL, NULL),
       (40, 'Ajax', NULL, NULL),
       (41, 'Alice', NULL, NULL),
       (42, 'Allemand', NULL, NULL),
       (43, 'Alpine.js', NULL, NULL),
       (44, 'Amazon Aurora', NULL, NULL),
       (45, 'Amazon DynamoDB', NULL, NULL),
       (46, 'Amazon RDS', NULL, NULL),
       (47, 'Amazon Redshift', NULL, NULL),
       (48, 'Amazon Web Services', NULL, NULL),
       (49, 'Amélioration continue', NULL, NULL),
       (50, 'Analyse de données', NULL, NULL),
       (51, 'Analyse de risques', NULL, NULL),
       (52, 'Android', NULL, NULL),
       (53, 'Android SDK', NULL, NULL),
       (54, 'Android Studio', NULL, NULL),
       (55, 'Android Wear', NULL, NULL),
       (56, 'Anglais', NULL, NULL),
       (57, 'Angular', NULL, NULL),
       (58, 'AngularJS', NULL, NULL),
       (59, 'Animation', NULL, NULL),
       (60, 'Animation 3D', NULL, NULL),
       (61, 'Ansible', NULL, NULL),
       (62, 'Apache', NULL, NULL),
       (63, 'Apache BeeHive', NULL, NULL),
       (64, 'Apache Camel', NULL, NULL),
       (65, 'Apache Flume', NULL, NULL),
       (66, 'Apache Kafka', NULL, NULL),
       (67, 'Apache Spark MLlib', NULL, NULL),
       (68, 'Apache Tapestry', NULL, NULL),
       (69, 'Apache Tomcat', NULL, NULL),
       (70, 'Apache struts', NULL, NULL),
       (71, 'Apache subversion', NULL, NULL),
       (72, 'AppDynamics', NULL, NULL),
       (73, 'Appium', NULL, NULL),
       (74, 'Apple TV', NULL, NULL),
       (75, 'Apple Watch', NULL, NULL),
       (76, 'Application Mobile', NULL, NULL),
       (77, 'Appolo', NULL, NULL),
       (78, 'Arabe', NULL, NULL),
       (79, 'Architecture SI', NULL, NULL),
       (80, 'Architecture distribuée', NULL, NULL),
       (81, 'Architecture web', NULL, NULL),
       (82, 'Arduino', NULL, NULL),
       (83, 'Arnold', NULL, NULL),
       (84, 'As3', NULL, NULL),
       (85, 'Assembleur', NULL, NULL),
       (86, 'AssertJ', NULL, NULL),
       (87, 'Atlas', NULL, NULL),
       (88, 'Atlassian Confluence', NULL, NULL),
       (89, 'Atlassian JIRA', NULL, NULL),
       (90, 'Atom', NULL, NULL),
       (91, 'Audacity', NULL, NULL),
       (92, 'Audiovisuel', NULL, NULL),
       (93, 'Audit', NULL, NULL),
       (94, 'Audit SEO', NULL, NULL),
       (95, 'Autocad', NULL, NULL),
       (96, 'Avid Pro Tools', NULL, NULL),
       (97, 'Awk', NULL, NULL),
       (98, 'Axure', NULL, NULL),
       (99, 'Backbone.js', NULL, NULL),
       (100, 'BackstopJS', NULL, NULL),
       (101, 'Balsamiq', NULL, NULL),
       (102, 'Bande dessinée', NULL, NULL),
       (103, 'Banque', NULL, NULL),
       (104, 'Bash', NULL, NULL),
       (105, 'Beanstalk', NULL, NULL),
       (106, 'Benchmark', NULL, NULL),
       (107, 'Big Data', NULL, NULL),
       (108, 'Big Query', NULL, NULL),
       (109, 'Bing Ads', NULL, NULL),
       (110, 'Bitcoin', NULL, NULL),
       (111, 'Blockchain', NULL, NULL),
       (112, 'Blog', NULL, NULL),
       (113, 'Bluetooth Low Energy', NULL, NULL),
       (114, 'Bootstrap', NULL, NULL),
       (115, 'Bottle', NULL, NULL),
       (116, 'Bower', NULL, NULL),
       (117, 'Brainstorming', NULL, NULL),
       (118, 'Brand content', NULL, NULL),
       (119, 'Branding', NULL, NULL),
       (120, 'Browserify', NULL, NULL),
       (121, 'Bug Bounty', NULL, NULL),
       (122, 'Buildbox', NULL, NULL),
       (123, 'Business analysis', NULL, NULL),
       (124, 'Business development', NULL, NULL),
       (125, 'Business intelligence', NULL, NULL),
       (126, 'Business model', NULL, NULL),
       (127, 'Business object', NULL, NULL),
       (128, 'Business plan', NULL, NULL),
       (129, 'C', NULL, NULL),
       (130, 'C#', NULL, NULL),
       (131, 'C++', NULL, NULL),
       (132, 'CAO', NULL, NULL),
       (133, 'CISSP', NULL, NULL),
       (134, 'CMS', NULL, NULL),
       (135, 'COBOL', NULL, NULL),
       (136, 'CRM', NULL, NULL),
       (137, 'CSRF', NULL, NULL),
       (138, 'CSS', NULL, NULL),
       (139, 'Cahier des charges', NULL, NULL),
       (140, 'Canvas', NULL, NULL),
       (141, 'Capistrano', NULL, NULL),
       (142, 'Carte de visite', NULL, NULL),
       (143, 'Cassandra', NULL, NULL),
       (144, 'Catalogue', NULL, NULL),
       (145, 'Charte graphique', NULL, NULL),
       (146, 'Chatbot', NULL, NULL),
       (147, 'Chef', NULL, NULL),
       (148, 'Chinois', NULL, NULL),
       (149, 'Cinéma', NULL, NULL),
       (150, 'Cisco', NULL, NULL),
       (151, 'Citrix', NULL, NULL),
       (152, 'Clara rules', NULL, NULL),
       (153, 'Clojure', NULL, NULL),
       (154, 'Cloud Engineer', NULL, NULL),
       (155, 'Cloud Spanner', NULL, NULL),
       (156, 'Cloud computing', NULL, NULL),
       (157, 'Coaching', NULL, NULL),
       (158, 'Coaching individuel', NULL, NULL),
       (159, 'Cocoa', NULL, NULL),
       (160, 'Cocoa Touch', NULL, NULL),
       (161, 'Coda', NULL, NULL),
       (162, 'Codeigniter', NULL, NULL),
       (163, 'Codéveloppement', NULL, NULL),
       (164, 'Commercial', NULL, NULL),
       (165, 'Communication', NULL, NULL),
       (166, 'Communication 360°', NULL, NULL),
       (167, 'Communication digitale', NULL, NULL),
       (168, 'Communication interne', NULL, NULL),
       (169, 'Communication print', NULL, NULL),
       (170, 'Communication visuelle', NULL, NULL),
       (171, 'Communiqué de presse', NULL, NULL),
       (172, 'Community management', NULL, NULL),
       (173, 'Comptabilité', NULL, NULL),
       (174, 'Conception', NULL, NULL),
       (175, 'Conception rédaction', NULL, NULL),
       (176, 'Conduite du changement', NULL, NULL),
       (177, 'Conseil', NULL, NULL),
       (178, 'Consul', NULL, NULL),
       (179, 'Contentful', NULL, NULL),
       (180, 'Contrôle de gestion', NULL, NULL),
       (181, 'Corda', NULL, NULL),
       (182, 'Cordova', NULL, NULL),
       (183, 'Correction', NULL, NULL),
       (184, 'Couchbase', NULL, NULL),
       (185, 'Crypto', NULL, NULL),
       (186, 'Créatif', NULL, NULL),
       (187, 'Création d\'entreprise', NULL, NULL),
       (188, 'Customer Journey', NULL, NULL),
       (189, 'Cybersécurité', NULL, NULL),
       (190, 'D', NULL, NULL),
       (191, 'DAO', NULL, NULL),
       (192, 'DBDeploy', NULL, NULL),
       (193, 'DDOS', NULL, NULL),
       (194, 'Dart', NULL, NULL),
       (195, 'Data Engineer', NULL, NULL),
       (196, 'Data Operating System Center', NULL, NULL),
       (197, 'Data mining', NULL, NULL),
       (198, 'Data science', NULL, NULL),
       (199, 'Data visualisation', NULL, NULL),
       (200, 'Administration de base de données', NULL, NULL),
       (201, 'Administratif', NULL, NULL),
       (202, 'Debian', NULL, NULL),
       (203, 'Deep Learning', NULL, NULL),
       (204, 'Deis', NULL, NULL),
       (205, 'Delphi', NULL, NULL),
       (206, 'Design', NULL, NULL),
       (207, 'Design Bannières', NULL, NULL),
       (208, 'Design Email', NULL, NULL),
       (209, 'Design Newsletter', NULL, NULL),
       (210, 'Design Tablette', NULL, NULL),
       (211, 'Design Thinking', NULL, NULL),
       (212, 'Design logo', NULL, NULL),
       (213, 'Design produit', NULL, NULL),
       (214, 'Dessin', NULL, NULL),
       (215, 'DevOps', NULL, NULL),
       (216, 'Direction artistique', NULL, NULL),
       (217, 'Display', NULL, NULL),
       (218, 'Django', NULL, NULL),
       (219, 'Docker', NULL, NULL),
       (220, 'Doctrine', NULL, NULL),
       (221, 'Dossier de presse', NULL, NULL),
       (222, 'Doubleclick', NULL, NULL),
       (223, 'Drools', NULL, NULL),
       (224, 'Drupal', NULL, NULL),
       (225, 'Drupal 7', NULL, NULL),
       (226, 'DynamoDB', NULL, NULL),
       (227, 'Développement', NULL, NULL),
       (228, 'Développement Back-End', NULL, NULL),
       (229, 'Développement Front-End', NULL, NULL),
       (230, 'Développement Mobile', NULL, NULL),
       (231, 'Développement produit', NULL, NULL),
       (232, 'Développement web', NULL, NULL),
       (233, 'E-commerce', NULL, NULL),
       (234, 'E-learning', NULL, NULL),
       (235, 'E-réputation', NULL, NULL),
       (236, 'EMQ', NULL, NULL),
       (237, 'ERP', NULL, NULL),
       (238, 'ETL', NULL, NULL),
       (239, 'Eclipse', NULL, NULL),
       (240, 'Edition', NULL, NULL),
       (241, 'Elasticsearch', NULL, NULL),
       (242, 'Elixir', NULL, NULL),
       (243, 'Elm', NULL, NULL),
       (244, 'Email marketing', NULL, NULL),
       (245, 'Emailing', NULL, NULL),
       (246, 'Ember.js', NULL, NULL),
       (247, 'Enzyme', NULL, NULL),
       (248, 'Erlang', NULL, NULL),
       (249, 'Espagnol', NULL, NULL),
       (250, 'Essbase', NULL, NULL),
       (251, 'Etude de besoin', NULL, NULL),
       (252, 'Etude de faisabilité', NULL, NULL),
       (253, 'Etude de marché', NULL, NULL),
       (254, 'Etude marketing', NULL, NULL),
       (255, 'Evénementiel', NULL, NULL),
       (256, 'Express', NULL, NULL),
       (257, 'Ext.js', NULL, NULL),
       (258, 'Extbase', NULL, NULL),
       (259, 'F#', NULL, NULL),
       (260, 'Facebook', NULL, NULL),
       (261, 'Facebook Marketing', NULL, NULL),
       (262, 'Facilitation de processus', NULL, NULL),
       (263, 'Fidélisation', NULL, NULL),
       (264, 'Film d\'entreprise', NULL, NULL),
       (265, 'Finance', NULL, NULL),
       (266, 'Firebase', NULL, NULL),
       (267, 'Flat Design', NULL, NULL),
       (268, 'Flood', NULL, NULL),
       (269, 'Flutter', NULL, NULL),
       (270, 'Flyer', NULL, NULL),
       (271, 'Formation', NULL, NULL),
       (272, 'Formation AdWords', NULL, NULL),
       (273, 'Formation Photoshop', NULL, NULL),
       (274, 'Formation Réseaux Sociaux', NULL, NULL),
       (275, 'Formation SEO', NULL, NULL),
       (276, 'Formation Wordpress', NULL, NULL),
       (277, 'Formation webmarketing', NULL, NULL),
       (278, 'Fortran', NULL, NULL),
       (279, 'Foundation', NULL, NULL),
       (280, 'Français', NULL, NULL),
       (281, 'FreeBSD', NULL, NULL),
       (282, 'Fuelphp', NULL, NULL),
       (283, 'Fullstack', NULL, NULL),
       (284, 'GIF', NULL, NULL),
       (285, 'GIMP', NULL, NULL),
       (286, 'GKE', NULL, NULL),
       (287, 'GO', NULL, NULL),
       (288, 'Game design', NULL, NULL),
       (289, 'Gamification', NULL, NULL),
       (290, 'Gestion de projet', NULL, NULL),
       (291, 'Gestion de projet technique', NULL, NULL),
       (292, 'Gestion de projet web', NULL, NULL),
       (293, 'Gestion des stocks', NULL, NULL),
       (294, 'Git', NULL, NULL),
       (295, 'Git-SVN', NULL, NULL),
       (296, 'GitHub', NULL, NULL),
       (297, 'Gobot', NULL, NULL),
       (298, 'Godot', NULL, NULL),
       (299, 'Google AdSense', NULL, NULL),
       (300, 'Google AdWords', NULL, NULL),
       (301, 'Google Analytics', NULL, NULL),
       (302, 'Google App Engine', NULL, NULL),
       (303, 'Google Search Console', NULL, NULL),
       (304, 'Google Shopping', NULL, NULL),
       (305, 'Google Tag Manager', NULL, NULL),
       (306, 'Google charts', NULL, NULL),
       (307, 'Google cloud', NULL, NULL),
       (308, 'Grails', NULL, NULL),
       (309, 'Graphisme', NULL, NULL),
       (310, 'Graphisme 3D', NULL, NULL),
       (311, 'Graphisme print', NULL, NULL),
       (312, 'Groovy', NULL, NULL),
       (313, 'Growth hacking', NULL, NULL),
       (314, 'Grunt', NULL, NULL),
       (315, 'Gulp', NULL, NULL),
       (316, 'Génération de leads', NULL, NULL),
       (317, 'HBase', NULL, NULL),
       (318, 'HPUX', NULL, NULL),
       (319, 'HTML', NULL, NULL),
       (320, 'HTML5', NULL, NULL),
       (321, 'HaProxy', NULL, NULL),
       (322, 'Hadoop', NULL, NULL),
       (323, 'Handlebars', NULL, NULL),
       (324, 'Haskell', NULL, NULL),
       (325, 'Helm', NULL, NULL),
       (326, 'Heroku', NULL, NULL),
       (327, 'Hibernate', NULL, NULL),
       (328, 'Highcharts', NULL, NULL),
       (329, 'Hive', NULL, NULL),
       (330, 'Houdini', NULL, NULL),
       (331, 'Hyperapp', NULL, NULL),
       (332, 'Hyperledger', NULL, NULL),
       (333, 'IAAS', NULL, NULL),
       (334, 'IBM Db2', NULL, NULL),
       (335, 'IIS', NULL, NULL),
       (336, 'ISO 14001', NULL, NULL),
       (337, 'ISO 26000', NULL, NULL),
       (338, 'ISO 27001', NULL, NULL),
       (339, 'ISO 9000', NULL, NULL),
       (340, 'ISO 9001', NULL, NULL),
       (341, 'Icônes', NULL, NULL),
       (342, 'Identité visuelle', NULL, NULL),
       (343, 'Illustration', NULL, NULL),
       (344, 'Illustration 3D', NULL, NULL),
       (345, 'Immobilier', NULL, NULL),
       (346, 'Impression 3D', NULL, NULL),
       (347, 'Inbound marketing', NULL, NULL),
       (348, 'Inertia', NULL, NULL),
       (349, 'InfluxDB', NULL, NULL),
       (350, 'Infographie', NULL, NULL),
       (351, 'Innovation', NULL, NULL),
       (352, 'Instagram', NULL, NULL),
       (353, 'Instagram Marketing', NULL, NULL),
       (354, 'IntelliJ', NULL, NULL),
       (355, 'Intelligence collective', NULL, NULL),
       (356, 'Interledger', NULL, NULL),
       (357, 'Internet des objets', NULL, NULL),
       (358, 'Interprète', NULL, NULL),
       (359, 'Intégration Responsive', NULL, NULL),
       (360, 'Intégration continue', NULL, NULL),
       (361, 'Intégration web', NULL, NULL),
       (362, 'Invision', NULL, NULL),
       (363, 'Ionic', NULL, NULL),
       (364, 'Iptables', NULL, NULL),
       (365, 'Italien', NULL, NULL),
       (366, 'JADE', NULL, NULL),
       (367, 'JSON', NULL, NULL),
       (368, 'Japonais', NULL, NULL),
       (369, 'Java', NULL, NULL),
       (370, 'JavaScript', NULL, NULL),
       (371, 'JavaServer Faces', NULL, NULL),
       (372, 'Jboss', NULL, NULL),
       (373, 'Jenkins', NULL, NULL),
       (374, 'Jeux vidéos', NULL, NULL),
       (375, 'Joomla', NULL, NULL),
       (376, 'Journalisme', NULL, NULL),
       (377, 'Julia', NULL, NULL),
       (378, 'Jupyter', NULL, NULL),
       (379, 'Kakémono', NULL, NULL),
       (380, 'Kanban', NULL, NULL),
       (381, 'Kettle', NULL, NULL),
       (382, 'Keycloak', NULL, NULL),
       (383, 'Kibana', NULL, NULL),
       (384, 'Komodo', NULL, NULL),
       (385, 'Kong', NULL, NULL),
       (386, 'Kotlin', NULL, NULL),
       (387, 'Kubernetes', NULL, NULL),
       (388, 'LAMP', NULL, NULL),
       (389, 'LESS', NULL, NULL),
       (390, 'LFI/RFI', NULL, NULL),
       (391, 'Labview', NULL, NULL),
       (392, 'Landing page', NULL, NULL),
       (393, 'Laravel', NULL, NULL),
       (394, 'Lean management', NULL, NULL),
       (395, 'Lean six sigma', NULL, NULL),
       (396, 'Lean startup', NULL, NULL),
       (397, 'Learning Management System', NULL, NULL),
       (398, 'Levée de fonds', NULL, NULL),
       (399, 'Liens sponsorisés', NULL, NULL),
       (400, 'Liferay', NULL, NULL),
       (401, 'LinkedIn', NULL, NULL),
       (402, 'LinkedIn Marketing', NULL, NULL),
       (403, 'Linux', NULL, NULL),
       (404, 'Liquibase', NULL, NULL),
       (405, 'Lisp', NULL, NULL),
       (406, 'LoRaWan', NULL, NULL),
       (407, 'LoadRunner', NULL, NULL),
       (408, 'Lua', NULL, NULL),
       (409, 'Lutèce', NULL, NULL),
       (410, 'Luxe', NULL, NULL),
       (411, 'MOA', NULL, NULL),
       (412, 'MOE', NULL, NULL),
       (413, 'MOOC', NULL, NULL),
       (414, 'MVC', NULL, NULL),
       (415, 'Machine learning', NULL, NULL),
       (416, 'Magazine', NULL, NULL),
       (417, 'Magento', NULL, NULL),
       (418, 'Mahout', NULL, NULL),
       (419, 'Mailchimp', NULL, NULL),
       (420, 'Mailjet', NULL, NULL),
       (421, 'Mailpro', NULL, NULL),
       (422, 'Mambo', NULL, NULL),
       (423, 'Management d\'équipe', NULL, NULL),
       (424, 'MapReduce', NULL, NULL),
       (425, 'Marin Software', NULL, NULL),
       (426, 'Marketing', NULL, NULL),
       (427, 'Marketing Intelligence', NULL, NULL),
       (428, 'Marketing de contenu', NULL, NULL),
       (429, 'Marketing direct', NULL, NULL),
       (430, 'Marketplace', NULL, NULL),
       (431, 'Material Design', NULL, NULL),
       (432, 'Matlab', NULL, NULL),
       (433, 'Maven', NULL, NULL),
       (434, 'Maya', NULL, NULL),
       (435, 'Memcached', NULL, NULL),
       (436, 'Mesos', NULL, NULL),
       (437, 'Messenger', NULL, NULL),
       (438, 'Meteor.js', NULL, NULL),
       (439, 'Microsoft Access', NULL, NULL),
       (440, 'Microsoft Azure', NULL, NULL),
       (441, 'Microsoft Excel', NULL, NULL),
       (442, 'Microsoft Exchange', NULL, NULL),
       (443, 'Microsoft Office', NULL, NULL),
       (444, 'Microsoft Power BI', NULL, NULL),
       (445, 'Microsoft Powerpoint', NULL, NULL),
       (446, 'Microsoft Project', NULL, NULL),
       (447, 'Microsoft Sharepoint', NULL, NULL),
       (448, 'Microsoft Visio', NULL, NULL),
       (449, 'Microsoft Visual Studio', NULL, NULL),
       (450, 'Microsoft Word', NULL, NULL),
       (451, 'Mise en page', NULL, NULL),
       (452, 'Mixpanel', NULL, NULL),
       (453, 'Mobile Design', NULL, NULL),
       (454, 'Mobile first', NULL, NULL),
       (455, 'Mobile marketing', NULL, NULL),
       (456, 'Mode', NULL, NULL),
       (457, 'MongoDB', NULL, NULL),
       (458, 'Mongoose OS', NULL, NULL),
       (459, 'Montage photo', NULL, NULL),
       (460, 'Montage son', NULL, NULL),
       (461, 'Montage vidéo', NULL, NULL),
       (462, 'Moodboard', NULL, NULL),
       (463, 'Motion design', NULL, NULL),
       (464, 'Mustache', NULL, NULL),
       (465, 'Muséographie', NULL, NULL),
       (466, 'MySQL', NULL, NULL),
       (467, 'Myposeo', NULL, NULL),
       (468, 'Médias', NULL, NULL),
       (469, 'Méthode agile', NULL, NULL),
       (470, 'NFC', NULL, NULL),
       (471, 'NHibernate', NULL, NULL),
       (472, 'NLP', NULL, NULL),
       (473, 'NPM', NULL, NULL),
       (474, 'Neo4j', NULL, NULL),
       (475, 'Neolane', NULL, NULL),
       (476, 'Netbeans', NULL, NULL),
       (477, 'Netlify', NULL, NULL),
       (478, 'Netlinking SEO', NULL, NULL),
       (479, 'Nginx', NULL, NULL),
       (480, 'Nltk', NULL, NULL),
       (481, 'Node.js', NULL, NULL),
       (482, 'Nuxt.js', NULL, NULL),
       (483, 'Négociation', NULL, NULL),
       (484, 'OAuth', NULL, NULL),
       (485, 'OLAP', NULL, NULL),
       (486, 'OWASP', NULL, NULL),
       (487, 'Objective-C', NULL, NULL),
       (488, 'Objets connectés', NULL, NULL),
       (489, 'Objets publicitaires', NULL, NULL),
       (490, 'Ocaml', NULL, NULL),
       (491, 'Office 365', NULL, NULL),
       (492, 'OpenZeppelin', NULL, NULL),
       (493, 'Openstack', NULL, NULL),
       (494, 'Optimisation Off-Page', NULL, NULL),
       (495, 'Optimisation On-Page', NULL, NULL),
       (496, 'Optimizely', NULL, NULL),
       (497, 'Oracle', NULL, NULL),
       (498, 'OrientDB', NULL, NULL),
       (499, 'PAAS', NULL, NULL),
       (500, 'PAO', NULL, NULL),
       (501, 'PCI DSS', NULL, NULL),
       (502, 'PHP', NULL, NULL),
       (503, 'PHP 5', NULL, NULL),
       (504, 'PHPUnit', NULL, NULL),
       (505, 'PL/SQL', NULL, NULL),
       (506, 'PMO', NULL, NULL),
       (507, 'Packaging', NULL, NULL),
       (508, 'Packshot', NULL, NULL),
       (509, 'Pandas', NULL, NULL),
       (510, 'Parse', NULL, NULL),
       (511, 'Partenariats', NULL, NULL),
       (512, 'PenTest', NULL, NULL),
       (513, 'Perl', NULL, NULL),
       (514, 'Phalcon', NULL, NULL),
       (515, 'Phonegap', NULL, NULL),
       (516, 'Photographie', NULL, NULL),
       (517, 'PhpStorm', NULL, NULL),
       (518, 'Pig', NULL, NULL),
       (519, 'Pinterest', NULL, NULL),
       (520, 'Pitch', NULL, NULL),
       (521, 'Pivotal Cloud Foundry', NULL, NULL),
       (522, 'Planning stratégique', NULL, NULL),
       (523, 'Plaquette', NULL, NULL),
       (524, 'Play framework', NULL, NULL),
       (525, 'Plugin Wordpress', NULL, NULL),
       (526, 'Portrait', NULL, NULL),
       (527, 'Portugais', NULL, NULL),
       (528, 'Post production', NULL, NULL),
       (529, 'PostgreSQL', NULL, NULL),
       (530, 'Postscript', NULL, NULL),
       (531, 'Powershell', NULL, NULL),
       (532, 'Presse', NULL, NULL),
       (533, 'Presse Magazine', NULL, NULL),
       (534, 'Prestashop', NULL, NULL),
       (535, 'Product management', NULL, NULL),
       (536, 'Prolog', NULL, NULL),
       (537, 'Prometheus', NULL, NULL),
       (538, 'Prototype', NULL, NULL),
       (539, 'Publicité', NULL, NULL),
       (540, 'Puppet', NULL, NULL),
       (541, 'Pycharm', NULL, NULL),
       (542, 'Python', NULL, NULL),
       (543, 'Pytorch', NULL, NULL),
       (544, 'Qlik', NULL, NULL),
       (545, 'R', NULL, NULL),
       (546, 'REST', NULL, NULL),
       (547, 'RIBs', NULL, NULL),
       (548, 'ROI', NULL, NULL),
       (549, 'RSSI', NULL, NULL),
       (550, 'RStudio', NULL, NULL),
       (551, 'RTB', NULL, NULL),
       (552, 'RTOS', NULL, NULL),
       (553, 'RabbitMQ', NULL, NULL),
       (554, 'Rancher', NULL, NULL),
       (555, 'Ranks', NULL, NULL),
       (556, 'Rasa', NULL, NULL),
       (557, 'Raspberry Pi', NULL, NULL),
       (558, 'React Native', NULL, NULL),
       (559, 'React.js', NULL, NULL),
       (560, 'Reactor', NULL, NULL),
       (561, 'Realm', NULL, NULL),
       (562, 'Recette fonctionnelle', NULL, NULL),
       (563, 'Recette technique', NULL, NULL),
       (564, 'Recrutement', NULL, NULL),
       (565, 'Redis', NULL, NULL),
       (566, 'Relations presse', NULL, NULL),
       (567, 'Relecture', NULL, NULL),
       (568, 'Reportage', NULL, NULL),
       (569, 'Reporting', NULL, NULL),
       (570, 'Responsive design', NULL, NULL),
       (571, 'Ressources humaines', NULL, NULL),
       (572, 'Retargeting', NULL, NULL),
       (573, 'Retouche photo', NULL, NULL),
       (574, 'Revenue Management', NULL, NULL),
       (575, 'Riak', NULL, NULL),
       (576, 'Ruby', NULL, NULL),
       (577, 'Ruby on Rails', NULL, NULL),
       (578, 'Russe', NULL, NULL),
       (579, 'Rust', NULL, NULL),
       (580, 'RxJS', NULL, NULL),
       (581, 'Réalisation vidéo', NULL, NULL),
       (582, 'Réalité virtuelle', NULL, NULL),
       (583, 'Rédaction', NULL, NULL),
       (584, 'Rédaction SEO', NULL, NULL),
       (585, 'Rédaction web', NULL, NULL),
       (586, 'Réduction des coûts', NULL, NULL),
       (587, 'Réponse à appel d\'offre', NULL, NULL),
       (588, 'Réseaux sociaux', NULL, NULL),
       (589, 'SAAS', NULL, NULL),
       (590, 'SAP', NULL, NULL),
       (591, 'SAP Business Objects', NULL, NULL),
       (592, 'SAP CRM', NULL, NULL),
       (593, 'SAP développement', NULL, NULL),
       (594, 'SAS', NULL, NULL),
       (595, 'SASS', NULL, NULL),
       (596, 'SEA', NULL, NULL),
       (597, 'SEM', NULL, NULL),
       (598, 'SEMrush', NULL, NULL),
       (599, 'SEO', NULL, NULL),
       (600, 'SEO Moz', NULL, NULL),
       (601, 'SMO', NULL, NULL),
       (602, 'SOA', NULL, NULL),
       (603, 'SOAP', NULL, NULL),
       (604, 'SQL', NULL, NULL),
       (605, 'SQL Injection', NULL, NULL),
       (606, 'SQL Server', NULL, NULL),
       (607, 'SQLite', NULL, NULL),
       (608, 'SSL', NULL, NULL),
       (609, 'SSO', NULL, NULL),
       (610, 'SVG', NULL, NULL),
       (611, 'Sage', NULL, NULL),
       (612, 'Salesforce', NULL, NULL),
       (613, 'Saltstack', NULL, NULL),
       (614, 'Santé', NULL, NULL),
       (615, 'Sarbacane', NULL, NULL),
       (616, 'Scala', NULL, NULL),
       (617, 'Scheme', NULL, NULL),
       (618, 'Schéma Directeur SI', NULL, NULL),
       (619, 'Scikit-learn', NULL, NULL),
       (620, 'Scout2', NULL, NULL),
       (621, 'Scratch', NULL, NULL),
       (622, 'Scrum', NULL, NULL),
       (623, 'Scénographie', NULL, NULL),
       (624, 'Seam', NULL, NULL),
       (625, 'Segment', NULL, NULL),
       (626, 'Sentry', NULL, NULL),
       (627, 'Serious Game', NULL, NULL),
       (628, 'Serverless', NULL, NULL),
       (629, 'Service client', NULL, NULL),
       (630, 'Servlet', NULL, NULL),
       (631, 'Shark', NULL, NULL),
       (632, 'Shopify', NULL, NULL),
       (633, 'Showreel', NULL, NULL),
       (634, 'Site vitrine', NULL, NULL),
       (635, 'Sketch', NULL, NULL),
       (636, 'Sketchup', NULL, NULL),
       (637, 'Smart Contract', NULL, NULL),
       (638, 'Smartphone', NULL, NULL),
       (639, 'SolidWorks', NULL, NULL),
       (640, 'Solidity', NULL, NULL),
       (641, 'Sound design', NULL, NULL),
       (642, 'Sourcing', NULL, NULL),
       (643, 'Sous-titrage', NULL, NULL),
       (644, 'Spark', NULL, NULL),
       (645, 'Spip', NULL, NULL),
       (646, 'Spring', NULL, NULL),
       (647, 'Spring MVC', NULL, NULL),
       (648, 'Spring Security', NULL, NULL),
       (649, 'Spring boot', NULL, NULL),
       (650, 'Spring.NET', NULL, NULL),
       (651, 'Spécifications fonctionnelles', NULL, NULL),
       (652, 'Spécifications techniques', NULL, NULL),
       (653, 'Start-up', NULL, NULL),
       (654, 'Stencil', NULL, NULL),
       (655, 'Stimulus', NULL, NULL),
       (656, 'Storm', NULL, NULL),
       (657, 'Storyboard', NULL, NULL),
       (658, 'Storytelling', NULL, NULL),
       (659, 'Stratégie SI', NULL, NULL),
       (660, 'Stratégie commerciale', NULL, NULL),
       (661, 'Stratégie d\'entreprise', NULL, NULL),
       (662, 'Stratégie de communication', NULL, NULL),
       (663, 'Stratégie de positionnement', NULL, NULL),
       (664, 'Stratégie de prix', NULL, NULL),
       (665, 'Stratégie webmarketing', NULL, NULL),
       (666, 'Stratégie éditoriale', NULL, NULL),
       (667, 'Stripe Connect', NULL, NULL),
       (668, 'SunOS', NULL, NULL),
       (669, 'Supply chain', NULL, NULL),
       (670, 'Svelte', NULL, NULL),
       (671, 'Swashbuckle', NULL, NULL),
       (672, 'Swift', NULL, NULL),
       (673, 'SwiftNIO', NULL, NULL),
       (674, 'Sybase', NULL, NULL),
       (675, 'Symfony', NULL, NULL),
       (676, 'Systèmes embarqués', NULL, NULL),
       (677, 'TDD', NULL, NULL),
       (678, 'TIBCO Spotfire', NULL, NULL),
       (679, 'TLS', NULL, NULL),
       (680, 'TYPO3', NULL, NULL),
       (681, 'Tableau software', NULL, NULL),
       (682, 'Tablette', NULL, NULL),
       (683, 'Tag Commander', NULL, NULL),
       (684, 'Talend', NULL, NULL),
       (685, 'Tcl', NULL, NULL),
       (686, 'TensorFlow', NULL, NULL),
       (687, 'Terradata', NULL, NULL),
       (688, 'Terraform', NULL, NULL),
       (689, 'Text mining', NULL, NULL),
       (690, 'TextMate', NULL, NULL),
       (691, 'Textile', NULL, NULL),
       (692, 'Tick Stack', NULL, NULL),
       (693, 'Titanium', NULL, NULL),
       (694, 'Tournage', NULL, NULL),
       (695, 'Traduction', NULL, NULL),
       (696, 'Traduction Allemand Anglais', NULL, NULL),
       (697, 'Traduction Allemand Français', NULL, NULL),
       (698, 'Traduction Anglais Allemand', NULL, NULL),
       (699, 'Traduction Anglais Français', NULL, NULL),
       (700, 'Traduction Anglais-Espagnol', NULL, NULL),
       (701, 'Traduction Arabe Français', NULL, NULL),
       (702, 'Traduction Catalan Français', NULL, NULL),
       (703, 'Traduction Chinois Français', NULL, NULL),
       (704, 'Traduction Croate Français', NULL, NULL),
       (705, 'Traduction Danois Français', NULL, NULL),
       (706, 'Traduction Espagnol Anglais', NULL, NULL),
       (707, 'Traduction Espagnol Français', NULL, NULL),
       (708, 'Traduction Français Allemand', NULL, NULL),
       (709, 'Traduction Français Anglais', NULL, NULL),
       (710, 'Traduction Français Arabe', NULL, NULL),
       (711, 'Traduction Français Catalan', NULL, NULL),
       (712, 'Traduction Français Chinois', NULL, NULL),
       (713, 'Traduction Français Croate', NULL, NULL),
       (714, 'Traduction Français Danois', NULL, NULL),
       (715, 'Traduction Français Espagnol', NULL, NULL),
       (716, 'Traduction Français Italien', NULL, NULL),
       (717, 'Traduction Français Japonais', NULL, NULL),
       (718, 'Traduction Français Portugais', NULL, NULL),
       (719, 'Traduction Français Russe', NULL, NULL),
       (720, 'Traduction Italien Français', NULL, NULL),
       (721, 'Traduction Japonais Français', NULL, NULL),
       (722, 'Traduction Portugais Français', NULL, NULL),
       (723, 'Traduction Russe Français', NULL, NULL),
       (724, 'Traffic Management', NULL, NULL),
       (725, 'Transact-SQL', NULL, NULL),
       (726, 'Transformation digitale', NULL, NULL),
       (727, 'Trello', NULL, NULL),
       (728, 'Truffle', NULL, NULL),
       (729, 'Turbopy', NULL, NULL),
       (730, 'Twisted', NULL, NULL),
       (731, 'Twitter', NULL, NULL),
       (732, 'Typescript', NULL, NULL),
       (733, 'Typographie', NULL, NULL),
       (734, 'UML', NULL, NULL),
       (735, 'UNIX', NULL, NULL),
       (736, 'Ubuntu', NULL, NULL),
       (737, 'Underscore', NULL, NULL),
       (738, 'Unity', NULL, NULL),
       (739, 'Unity 3D', NULL, NULL),
       (740, 'Urbanisme SI', NULL, NULL),
       (741, 'User Experience Design', NULL, NULL),
       (742, 'User Interface Design', NULL, NULL),
       (743, 'User Research', NULL, NULL),
       (744, 'User Testing', NULL, NULL),
       (745, 'VB.NET', NULL, NULL),
       (746, 'VBA', NULL, NULL),
       (747, 'VMWARE', NULL, NULL),
       (748, 'Vagrant', NULL, NULL),
       (749, 'Varnish', NULL, NULL),
       (750, 'Vault', NULL, NULL),
       (751, 'Veille concurrentielle', NULL, NULL),
       (752, 'Viadéo', NULL, NULL),
       (753, 'Viadéo Marketing', NULL, NULL),
       (754, 'Vidéo', NULL, NULL),
       (755, 'Vim', NULL, NULL),
       (756, 'VirtualBox', NULL, NULL),
       (757, 'Virtualisation', NULL, NULL),
       (758, 'Visual Basic', NULL, NULL),
       (759, 'Visual management', NULL, NULL),
       (760, 'Vue.js', NULL, NULL),
       (761, 'WINDEV', NULL, NULL),
       (762, 'Web Bluetooth API', NULL, NULL),
       (763, 'Web analytics', NULL, NULL),
       (764, 'WebAssembly', NULL, NULL),
       (765, 'WebGL', NULL, NULL),
       (766, 'WebSphere', NULL, NULL),
       (767, 'Webdesign', NULL, NULL),
       (768, 'Webmarketing', NULL, NULL),
       (769, 'Webmastering', NULL, NULL),
       (770, 'Websocket', NULL, NULL),
       (771, 'Windows 10', NULL, NULL),
       (772, 'Windows Containers', NULL, NULL),
       (773, 'Windows Phone', NULL, NULL),
       (774, 'Windows Presentation Foundation', NULL, NULL),
       (775, 'Windows Server', NULL, NULL),
       (776, 'Wireframing', NULL, NULL),
       (777, 'Wiremock', NULL, NULL),
       (778, 'WooCommerce', NULL, NULL),
       (779, 'Wordpress', NULL, NULL),
       (780, 'XML', NULL, NULL),
       (781, 'XSS', NULL, NULL),
       (782, 'Xamarin', NULL, NULL),
       (783, 'Xcode', NULL, NULL),
       (784, 'Xiti', NULL, NULL),
       (785, 'Yii', NULL, NULL),
       (786, 'Yooda', NULL, NULL),
       (787, 'Zbrush', NULL, NULL),
       (788, 'Zend', NULL, NULL),
       (789, 'Zend 2', NULL, NULL),
       (790, 'cakePHP', NULL, NULL),
       (791, 'd3.js', NULL, NULL),
       (792, 'directeur', NULL, NULL),
       (793, 'eZ Publish', NULL, NULL),
       (794, 'flink', NULL, NULL),
       (795, 'gephi', NULL, NULL),
       (796, 'iOS', NULL, NULL),
       (797, 'iPad', NULL, NULL),
       (798, 'iPhone', NULL, NULL),
       (799, 'impact.js', NULL, NULL),
       (800, 'jQuery', NULL, NULL),
       (801, 'jqPlot', NULL, NULL),
       (802, 'noSQL', NULL, NULL),
       (803, 'odoo', NULL, NULL),
       (804, 'phpMyAdmin', NULL, NULL),
       (805, 'redux', NULL, NULL),
       (806, 'soir', NULL, NULL),
       (807, 'three.js', NULL, NULL),
       (808, 'troposphere', NULL, NULL),
       (809, 'weka', NULL, NULL),
       (810, 'zookeeper', NULL, NULL);