/* Replace with your SQL commands */

INSERT INTO `reference`
VALUES (1, 'JavaScript',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/1200px-Unofficial_JavaScript_logo_2.svg.png',
        'https://developer.mozilla.org/fr/docs/Web/JavaScript'),
       (2, 'React',
        'https://static.formation.tech/formations/logos/889d72ed4da481c24ef573c9098b1a99.svg',
        'https://fr.reactjs.org/'),
       (3, 'Node.js\n',
        'https://blog.octo.com/wp-content/uploads/2018/01/node-300x300.jpg',
        'https://nodejs.org/en/'),
       (4, 'MySQL', 'https://upload.wikimedia.org/wikipedia/fr/6/62/MySQL.svg', 'https://www.mysql.com/fr/'),
       (5, 'Redux', 'https://makina-corpus.com/blog/metier/2016/pourquoi-vous-devriez-utiliser-les-selecteurs-avec-redux/image_mini',
        'https://redux.js.org/');

INSERT INTO `freelance_reference`
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (6, 1),
       (6, 2),
       (6, 3),
       (6, 4),
       (6, 5),
       (7, 1),
       (7, 2),
       (7, 3),
       (7, 4),
       (7, 5),
       (8, 1),
       (8, 2),
       (8, 3),
       (8, 4),
       (8, 5),
       (9, 1),
       (9, 2),
       (9, 3),
       (9, 4),
       (9, 5),
       (10, 1),
       (10, 2),
       (10, 3),
       (10, 4),
       (10, 5);

