/* Replace with your SQL commands */

UPDATE freelance SET freelance.url_photo= 'uploads/43.jpg' WHERE id = 1;
UPDATE freelance SET freelance.url_photo= 'uploads/23.jpg' WHERE id = 2;
UPDATE freelance SET freelance.url_photo= 'uploads/10.jpg' WHERE id = 3;
UPDATE freelance SET freelance.url_photo= 'uploads/87.jpg' WHERE id = 4;
UPDATE freelance SET freelance.url_photo= 'uploads/21.jpg' WHERE id = 5;
UPDATE freelance SET freelance.url_photo= 'uploads/1.jpg' WHERE id = 6;
UPDATE freelance SET freelance.url_photo= 'uploads/2.jpg' WHERE id = 7;
UPDATE freelance SET freelance.url_photo= 'uploads/22.jpg' WHERE id = 8;
UPDATE freelance SET freelance.url_photo= 'uploads/27.jpg' WHERE id = 9;
UPDATE freelance SET freelance.url_photo= 'uploads/22 (1).jpg' WHERE id = 10;
UPDATE freelance SET freelance.url_photo= 'uploads/3 (1).jpg' WHERE id = 11;
UPDATE freelance SET freelance.url_photo= 'uploads/89.jpg' WHERE id = 12;
UPDATE freelance SET freelance.url_photo= 'uploads/25.jpg' WHERE id = 13;
UPDATE freelance SET freelance.url_photo= 'uploads/39.jpg' WHERE id = 14;
UPDATE freelance SET freelance.url_photo= 'uploads/34.jpg' WHERE id = 15;
UPDATE freelance SET freelance.url_photo= 'uploads/3.jpg' WHERE id = 16;
UPDATE freelance SET freelance.url_photo= 'uploads/7.jpg' WHERE id = 17;
UPDATE freelance SET freelance.url_photo= 'uploads/36.jpg' WHERE id = 18;
UPDATE freelance SET freelance.url_photo= 'uploads/5.jpg' WHERE id = 19;
UPDATE freelance SET freelance.url_photo= 'uploads/23 (1).jpg' WHERE id = 20;

UPDATE freelance SET freelance.url_photo= 'uploads/43.jpg' WHERE id = 21;
UPDATE freelance SET freelance.url_photo= 'uploads/23.jpg' WHERE id = 22;
UPDATE freelance SET freelance.url_photo= 'uploads/10.jpg' WHERE id = 23;
UPDATE freelance SET freelance.url_photo= 'uploads/87.jpg' WHERE id = 24;
UPDATE freelance SET freelance.url_photo= 'uploads/21.jpg' WHERE id = 25;
UPDATE freelance SET freelance.url_photo= 'uploads/1.jpg' WHERE id = 26;
UPDATE freelance SET freelance.url_photo= 'uploads/2.jpg' WHERE id = 27;
UPDATE freelance SET freelance.url_photo= 'uploads/22.jpg' WHERE id = 28;
UPDATE freelance SET freelance.url_photo= 'uploads/27.jpg' WHERE id = 29;
UPDATE freelance SET freelance.url_photo= 'uploads/22 (1).jpg' WHERE id = 30;
UPDATE freelance SET freelance.url_photo= 'uploads/3 (1).jpg' WHERE id = 31;
UPDATE freelance SET freelance.url_photo= 'uploads/89.jpg' WHERE id = 32;
UPDATE freelance SET freelance.url_photo= 'uploads/25.jpg' WHERE id = 33;
UPDATE freelance SET freelance.url_photo= 'uploads/39.jpg' WHERE id = 34;
UPDATE freelance SET freelance.url_photo= 'uploads/34.jpg' WHERE id = 35;
UPDATE freelance SET freelance.url_photo= 'uploads/3.jpg' WHERE id = 36;
UPDATE freelance SET freelance.url_photo= 'uploads/7.jpg' WHERE id = 37;
UPDATE freelance SET freelance.url_photo= 'uploads/36.jpg' WHERE id = 38;
UPDATE freelance SET freelance.url_photo= 'uploads/5.jpg' WHERE id = 39;
UPDATE freelance SET freelance.url_photo= 'uploads/23 (1).jpg' WHERE id = 40;

UPDATE freelance SET freelance.url_photo= 'uploads/43.jpg' WHERE id = 41;
UPDATE freelance SET freelance.url_photo= 'uploads/23.jpg' WHERE id = 42;
UPDATE freelance SET freelance.url_photo= 'uploads/10.jpg' WHERE id = 43;
UPDATE freelance SET freelance.url_photo= 'uploads/87.jpg' WHERE id = 44;
UPDATE freelance SET freelance.url_photo= 'uploads/21.jpg' WHERE id = 45;
UPDATE freelance SET freelance.url_photo= 'uploads/1.jpg' WHERE id = 46;
UPDATE freelance SET freelance.url_photo= 'uploads/2.jpg' WHERE id = 47;
UPDATE freelance SET freelance.url_photo= 'uploads/22.jpg' WHERE id = 48;
UPDATE freelance SET freelance.url_photo= 'uploads/27.jpg' WHERE id = 49;
UPDATE freelance SET freelance.url_photo= 'uploads/22 (1).jpg' WHERE id = 50;
UPDATE freelance SET freelance.url_photo= 'uploads/3 (1).jpg' WHERE id = 51;
UPDATE freelance SET freelance.url_photo= 'uploads/89.jpg' WHERE id = 52;
UPDATE freelance SET freelance.url_photo= 'uploads/25.jpg' WHERE id = 53;
UPDATE freelance SET freelance.url_photo= 'uploads/39.jpg' WHERE id = 54;
UPDATE freelance SET freelance.url_photo= 'uploads/34.jpg' WHERE id = 55;
UPDATE freelance SET freelance.url_photo= 'uploads/3.jpg' WHERE id = 56;
UPDATE freelance SET freelance.url_photo= 'uploads/7.jpg' WHERE id = 57;
UPDATE freelance SET freelance.url_photo= 'uploads/36.jpg' WHERE id = 58;
UPDATE freelance SET freelance.url_photo= 'uploads/5.jpg' WHERE id = 59;
UPDATE freelance SET freelance.url_photo= 'uploads/23 (1).jpg' WHERE id = 60;

UPDATE reference SET image= 'uploads/1200px-Unofficial_JavaScript_logo_2.svg.png' WHERE id = 1;
UPDATE reference SET image= 'uploads/889d72ed4da481c24ef573c9098b1a99.svg' WHERE id = 2;
UPDATE reference SET image= 'uploads/node-300x300.jpg' WHERE id = 3;
UPDATE reference SET image= 'uploads/MySQL.svg' WHERE id = 4;
UPDATE reference SET image= 'uploads/image_mini.png' WHERE id = 5;