swagger: "2.0"
info:
  description: "Simple API to manage freelancers"
  version: "1.0.0"
  title: "Freelancers API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "freelancer"
  description: "operations on freelancers"
paths:
  /customers:
    get:
      tags:
      - "freelancer"
      summary: "Get a list of freelancers"
      description: ""
      responses:
        "200":
          description: "Everything went well"
          schema:
            type: 'object'
            properties:
              data:
                type: 'array'
                items: 
                  $ref: '#/definitions/FreelancerSimplified'
    post:
      tags:
      - "freelancer"
      summary: "Add a new freelancer"
      description: ""
      parameters:
      - in: "body"
        name: "freelancer"
        description: "Freelancer object that needs to be added in DB"
        required: true
        schema:
          allOf:
           - $ref: "#/definitions/FreelancerEditableAttributes"
           - type: 'object'
             required:
              - "email"
      responses:
        "201":
          description: "Created"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Freelancer"
        "400":
          description: "Invalid input. The freelancer object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
          
  /customers/{customerId}:
    get:
      tags:
      - "freelancer"
      summary: "Find a freelancer by ID"
      description: "Returns a single freelancer"
      parameters:
      - name: "freelancerId"
        in: "path"
        description: "ID of freelancer to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: 'object'
            properties:
              data:
                type: "object"
                $ref: "#/definitions/Freelancer"
        "404":
          description: "freelancer not found"
    put:
      tags:
      - "freelancer"
      summary: "Update an existing freelancer"
      description: ""
      parameters:
      - name: "freelancerId"
        in: "path"
        description: "ID of freelancer to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "freelancer"
        description: "freelancer object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/FreelancerEditableAttributes"
      responses:
        "200":
          description: "Updated"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Freelancer"
        "404":
          description: "freelancer not found"
        "400":
          description: "Invalid input. The customer object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
    delete:
      tags:
      - "freelancer"
      summary: "Deletes a freelancer"
      description: ""
      parameters:
      - name: "freelancerId"
        in: "path"
        description: "freelancer id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "freelancer not found"
        "200":
          description: "OK"
definitions:
  CustomerEditableAttributes:
    type: "object"
    properties:
      first_name:
        type: "string"
        example: "John"
      last_name:
        type: "string"
        example: "Doe"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  CustomerSimplified:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "John"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  Customer:
    allOf: 
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: '#/definitions/FreelancerEditableAttributes'
      